name: Build Firmware with Docker

on:
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ghcr.io/ftun-arch/immortalwrt:build-env
          push: true

  build-firmware:
    needs: build-docker-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ftun-arch/immortalwrt:build-env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare build configuration
        run: |
          cp msm89xx.config .config
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
      - name: Change ownership for build process
        run: |
          chown -R builder:builder .
      - name: Build firmware as non-root user
        run: |
          runuser -u builder -- make -j$(nproc) V=s
      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-firmware-msm8916
          path: bin/targets/
